# Use this in your UnturnedImages/config.yaml file
- Id: "19300-19343" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/3417764218/vehicles/{ItemId}.png" # The repository of the override.