# Use this in your UnturnedImages/config.yaml file
- WorkshopId: "1645090733" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/1645090733/vehicles/{VehicleId}.png" # The repository of the override.